name: story_page_view
description: Instagram style story page view.
version: 1.0.0
homepage: https://docs.flutter.dev/development/tools/sdk/releases?tab=macos

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: '>=1.17.0'

dependencies:
  flutter:
    sdk: flutter
  freezed_annotation: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  freezed: ^1.1.1
  build_runner: ^2.1.7

flutter:
